### ISSUE TITLE
As a developer, I want to see the commands that are being run behind the scenes so that I can more easily debug when things go wrong

### ISSUE THREAD

**Issue by cpliakas** [svolpe43/cfsh#8]
This tool is simply magical, which is awesome. This also makes it harder to debug when things go wrong or something unexpected happens. The goal is to provide some mechanism to see the underlying commands and API calls that this tool is abstracting to development and debugging purposes.

Not sure what the implementation is, whether that is a `--verbose` option to the individual commands, the same when starting the tool, some debug log capability, or something else. Again, the goal is to be able to more easily peek behind the curtain to see how the magic trick is being performed.

**Comment by svolpe43** [comment]
Holy shoot 20 days ago! I'm sorry I never saw this! Thank you so much for trying it out. This is great advice. I'm going to add logging levels so that a verbose options is possible.

**Comment by svolpe43** [comment]
Closing this for now until I can get some time to do this.
